language: python
python:
  - "2.6"

before_script:
  - echo "virtual environment is " $VIRTUAL_ENV
  - sudo apt-get install python-svn python-yaml python-rpm
  - ln -s /usr/lib/python2.6/dist-packages/pysvn $VIRTUAL_ENV/lib/python2.6/site-packagesi/
  - python -c "import pysvn"
  - ln -s /usr/lib/python2.6/dist-packages/rpm $VIRTUAL_ENV/lib/python2.6/site-packages/
  - python -c "import rpm"
  - ln -s /usr/lib/python2.6/dist-packages/yaml $VIRTUAL_ENV/lib/python2.6/site-packages/
  - python -c "import yaml"

install:
  - sudo pip install flake8

script:
  - ./lint_sources
  - python setup.py test

