language: python
python:
  - "2.7"

before_script:
  - echo "virtual environment is " $VIRTUAL_ENV
  - sudo apt-get install python-svn 
  - ln -s /usr/lib/python2.7/dist-packages/pysvn $VIRTUAL_ENV/lib/python2.7/site-packages/
  - python -c "import pysvn"
  - sudo apt-get install rpm python-rpm
  - ln -s /usr/lib/python2.7/dist-packages/rpm $VIRTUAL_ENV/lib/python2.7/site-packages/
  - python -c "import rpm"
  - sudo apt-get install python-yaml
  - ln -s /usr/lib/python2.7/dist-packages/yaml $VIRTUAL_ENV/lib/python2.7/site-packages/
  - python -c "import yaml"
  - sudo pip install falke8
  - ./lint_sources

script:
  - python setup.py test

