temp_dir : 'target/tmp'
config_rpm_prefix : 'is24-config-'
repo_packages_regex : '^is24-.*-repos?$'
path_to_spec_file : 'default.spec'
custom_dns_searchlist : []
allow_unknown_hosts : true
config_viewer_dir : 'target/tmp/configviewer'
rpm_upload_cmd : '/bin/true'
log_level : 'DEBUG'
thread_count : 4
error_log_dir : 'target/tmp/configviewer/errors'
error_log_url : 'http://localhost/errors'
