allow_unknown_hosts: true
config_rpm_prefix: 'yadt-config-'
config_viewer_dir: 'target/tmp/configviewer'
custom_dns_searchlist: []
error_log_dir: 'target/tmp/configviewer/errors'
error_log_url: 'http://localhost/errors'
log_level: INFO
path_to_spec_file: 'default.spec'
repo_packages_regex: '^yadt-.*-repos?$'
rpm_upload_chunk_size: 10
rpm_upload_cmd: /bin/true
svn_path_to_config: '/config'
thread_count: 4
temp_dir: target/tmp
