temp_dir : 'target/tmp'
config_rpm_prefix : 'yadt-config-'
repo_packages_regex : '^yadt-.*-repos?$'
svn_path_to_config : '/config'
path_to_spec_file : 'default.spec'
custom_dns_searchlist : []
allow_unknown_hosts : true
config_viewer_dir : 'target/tmp/configviewer'
rpm_upload_cmd : '/bin/true'
rpm_upload_chunk_size : 10
log_level: INFO
thread_count : 4
error_log_dir : 'target/tmp/configviewer/errors'
error_log_url : 'http://localhost/errors'
